language: swift
osx_image: xcode13.3

cache:
  bundler: true

install:
  - bundle install
script: 
  - echo "machine github.com login $GITHUB_API_TOKEN" >> ~/.netrc
  - bundle exec fastlane ios development --verbose
