workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1 # Specify the instance type, example: mac_mini_m1

    environment:
      xcode: latest # Specify Xcode version, example: 13.3
      groups:
        - default # Example group, add your API tokens here TESTAPPIO_API_TOKEN and TESTAPPIO_APP_ID

    scripts:

      # BUILD
      # Add your build commands here
      #...

      # UPLOAD
      - name: Upload to TestApp.io
        script: |
          #!/bin/bash

          # Download and install the TestApp.io CLI
          curl -Ls https://github.com/testappio/cli/releases/latest/download/install | bash

          # Use the TestApp.io CLI to publish the app
          ta-cli publish \
            --api_token=$TESTAPPIO_API_TOKEN \
            --app_id=$TESTAPPIO_APP_ID \
            --release="ios" \
            --ipa=./build/ios/ipa/app.ipa \
            --notify=true \
            --git_release_notes=true \
            --git_commit_id=true \
            --source="Codemagic"
