
version: 2.1

jobs:
  build:
    macos:
      xcode: 12.5.1 # Specify the Xcode version to use
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec fastlane ios development
workflows:
  sample: 
    jobs:
      - build
