version: 2.1

orbs:
  node: circleci/node@5.0

jobs:
  eas_ios_staging_build:
    macos:
      xcode: '15.0.0'
    steps:
      - checkout
      - run:
          name: Install Cocoapods
          command: gem install cocoapods
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: iOS build
          command: npx eas-cli build -p ios --profile staging --local --non-interactive --clear-cache --output "./ipa/ios-staging-build.ipa"

      - run:
          name: upload to TestApp.io
          command: |
            export INSTALL_DIR=/tmp
            curl -Ls https://github.com/testappio/cli/releases/latest/download/install | bash
            $INSTALL_DIR/ta-cli publish --api_token=$TESTAPPIO_API_TOKEN --app_id=$TESTAPPIO_APP_ID --release="ios" --ipa=./ipa/ios-staging-build.ipa --notify=true --git_release_notes=true --git_commit_id=true --source="Circle CI"

workflows:
  ios_staging_build:
    jobs:
      - eas_ios_staging_build:
          filters:
            branches:
              only: staging
